### ISSUE TITLE
Take the API to the next level

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#1]
this is a great start, but after using it, i'd like to see it take care of everything contract and augur.  the methods should take normal values like '0.02' and do the conversion to fixed point.  it should use whatever rpc interface it likes and it would be nice if it did sanity checking on inputs and good exceptions handles.

it so close to this already and i'm totally sold on this abstraction.

**Comment by tinybike** [comment]
Agree 100% with handling all the contract/augur details here.  I implemented both of your suggestions: all augur.js methods now accept and return normal values ("0.02", etc.) -- the fixed-point stuff is all handled internally.  So, from the client's point-of-view, all this base 2^64 silliness doesn't even exist!

(Tentatively declaring the API to be taken to the next level and closing this...)
