### ISSUE TITLE
Add function to get trading actions

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur.js#100]
Based on user's order, position and order book return what trading actions (BUY, SELL, BID, ASK, SHORT_SELL, SHORT_SELL_RISKY) will happen. Based on actions fee structure and potential profit/loss can be calculated.

**Comment by priecint** [comment]
https://docs.google.com/spreadsheets/d/1WDj12rn39i8RNwUnk93b3poCrQPrDsi0jYqqj9E5-Ts/

**Comment by tinybike** [comment]
Added in ddb0652d1e2656af54fe94f33146fc4d3cbc744d.
