### ISSUE TITLE
getAccountTrades should look at log_fill_tx, not log_price

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur.js#116]
`getAccountTrades` currently only works for one side of the trade (the one that filled the order), and it should be reporting both. This should be looking at `log_fill_tx` instead of `log_price`

**Comment by kevinday** [comment]
@tinybike before I go much further on this I'd like some feedback on my thinking so far: https://github.com/AugurProject/augur.js/blob/accountTrades/src/modules/logs.js#L126

Currently `getAccountTrades` only works for the `sender` of the trade, so I'm thinking in order to get a complete trade history for an account you need to fetch `log_fill_tx` twice - once where that account is the sender, and once where it's the owner. That's what I'm doing in the commit I referenced above.

It's close, but I don't think it's perfect - when I run this (the accounts are both sides of one trade):

```
var account = "0xad9bd4391f5d0e507db06c827a9b1581f8085cde";
augur.getAccountTrades(account, (trades) => {
	console.log("result: ", account, JSON.stringify(trades, null, 2));
	augur.getAccountTrades(account, (trades) => {
		account = "0x625af06be127679ed3df995d75a5e803f3510bd6";
		console.log("result: ", account, JSON.stringify(trades, null, 2));
	});
});
```
I now get results for both accounts which is good:

```
result:  0xad9bd4391f5d0e507db06c827a9b1581f8085cde {
  "0x7133a8fae202a87e9f46f860cb919bcde7325dce60b93f31f52ea52be54a2991": {
    "1": [
      {
        "type": 1,
        "market": "0x7133a8fae202a87e9f46f860cb919bcde7325dce60b93f31f52ea52be54a2991",
        "price": "0.01",
        "shares": "1",
        "trade_id": "0xc9f8c4c9965a84059f5c1b25816e27bfd723cc4116608ba6fa616dad126f998f",
        "blockNumber": 1337881
      }
    ]
  }
}
result:  0x625af06be127679ed3df995d75a5e803f3510bd6 {
  "0x7133a8fae202a87e9f46f860cb919bcde7325dce60b93f31f52ea52be54a2991": {
    "1": [
      {
        "type": 1,
        "market": "0x7133a8fae202a87e9f46f860cb919bcde7325dce60b93f31f52ea52be54a2991",
        "price": "0.01",
        "shares": "1",
        "trade_id": "0xc9f8c4c9965a84059f5c1b25816e27bfd723cc4116608ba6fa616dad126f998f",
        "blockNumber": 1337881
      }
    ]
  }
}
```
However the result is identical for both accounts which probably isn't ideal . Should I modify the result to add another field to indicate which side of the trade this entry is? Any other feedback?

**Comment by tinybike** [comment]
Good point, it would be good to note which side of the trade they took!  The easiest thing to do might be to add a `maker` field to each trade: set it to `true` if they were the maker, `false` if they were the taker.

**Comment by tinybike** [comment]
Updated in 37c8a2a7bfca58d1a08232ac9f2fc4f73208bba0
