### ISSUE TITLE
Remove log_price filters from augur.js

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur.js#117]
After talking with @joeykrug I don't see a reason why we need both `log_price` and `log_fill_tx`. He suggested that log_price can just be removed from the trade contract.

Before I do this, we should unwind all dependencies on log_price in augur.js and augur. There are two additional data items logged from log_price that aren't logged by log_fill_tx: `type`, and block.timestamp`. If we require these anywhere we should just be able to add them to `log_fill_tx`.

Assigning to myself and @tinybike.

**Comment by tinybike** [comment]
Removed in 3c183559ae3385226467e49f433a99d3ac16de26
