### ISSUE TITLE
use RPC call to determine what network we're using and switch to the appropriate contract address

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#19]
manually passing in network id is error prone and bad interface design if you can make an rpc call and determine it yourself.  please implement this and make the usage transparent on Augur.connect()

i think it's this call: https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version

**Comment by tinybike** [comment]
Good thinking!  I did not realize that this is what the `net_version` RPC call does.  Implemented in f672ca6d4e86ce60b4e85d4ce5d08a04b4340c36.  `Augur.connect()` now uses the private chain contracts automatically if `net_version` is `"1010101"`.

(You can still pass in a `chain` parameter; setting `chain: 1010101` forces augur.js to use the private chain contracts.)
