### ISSUE TITLE
decouple comments system from getMarketsInfo

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#22]
in an effort to further optimize loading markets, i'm using this contract method that returns several market properties at once.   it's doing some comment thing as well and spamming the logs as well.  i'd prefer to keep it as lean as possible and not do anything else while optimizing the market loading.

**Comment by tinybike** [comment]
Implemented in c80fb01fef20fca2aa6b912dc054bfae4d7511ef and 6cef3cfb4457aa1315b6bf02d85d7def18002c62.
