### ISSUE TITLE
Augur.getVotePeriod callback fire twice

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#23]
the callback fires twice. once with the correct value, once undefined.

**Comment by tinybike** [comment]
I'm having trouble reproducing this.  Can you paste the exact call you're making to getVotePeriod?

**Comment by tinybike** [comment]
I was not able to reproduce this error for getVotePeriod, but I did experience this for other methods.  Fixed in d580d5b17e492026665bd2583dc2277a7268ed00; re-open this issue if getVotePeriod continues to have this problem.
