### ISSUE TITLE
Be more delicate/smarter with string/byte type returns

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#25]
"he ultimate solution to global warming will be geoengineering (defined as a majority of research papers claiming this is why temps dropped)"

is not market 0x1607e87fb97385cc01690314169cf9c60b7e7e0a7498572612e9ee53ab3cbb7b description.

**Comment by tinybike** [comment]
Fixed in 6a4f2c3c81d2029c4f1b192f8a13fa5e9da025c4.
