### ISSUE TITLE
Augur.cashFaucet, Augur.repFaucet & other sendTransaction not actually sending

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#26]
None of these are actually producing a tx, silently failing and not firing an onSent.

**Comment by tinybike** [comment]
Updated cash.se + dependencies in 0b3cfecb187d63711c4aaf93b9c79e8ab7c835ba, which fixes cashFaucet.  Other sendTransactions seem to work ok -- augur.js passes its test suite (test/runtests) on both private chain and testnet.  If this keeps happening, re-open this issue and I'll troubleshoot further.
