### ISSUE TITLE
Uncaught Error: Callback was already called.

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#29]
getting this now with some call to augur.js.  happens right away when trying to load markets.

```called @ app.js:6068(anonymous function) @ app.js:32018module.exports.parse @ app.js:31939(anonymous function) @ app.js:31987```

**Comment by scottzer0** [comment]
Gonna reopen this as I'm seeing this exact error in augur.js in several places now.   I can consistently get it when trying to sell (but buy seemed to work) shares.

**Comment by tinybike** [comment]
Should be fixed in 6305d4d57a94b8d650a41f633df754905dbf466, but re-open this if it happens again.
