### ISSUE TITLE
Implement market comments

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#3]
Augur.addMarketComment({
   marketId: _hashId_/_BigNumber_
   author: _address_,
   message: _string_
})

Augur.getMarketComments(_marketId_)

this would store the the comment in an  associated centralized datastore, whisper network or ipfs with timestamp of course.

**Comment by tinybike** [comment]
Implemented decentralized comments in 2c42ef3459f9140836bb2286033b24caf2557c25.

This works by storing comments in the Ethereum LevelDB (comes w/ both eth and geth, not sure about pyeth) on the user's computer.  Comments themselves are sent out over Whisper.  Any time a user posts a new comment, they broadcast **all** comments from their LevelDB (for that market)

If you're viewing a market, you have a comment (Whisper) filter up automatically.  Setting up a filter -- and a timer that polls the filter as needed -- is now done automatically as part of getMarketInfo.  So filter setup and polling should "just happen" from the perspective of the UI.

Comments are synchronized among users.  Users may receive multiple incoming comments; they simply assume that the incoming message containing the **most** comments is the correct one, and they write that to their local LevelDB.

(Similar to Bitcoin consensus.  It lacks proof-of-work, but hey, these are just comments!)
