### ISSUE TITLE
some value from batch calls coming back in fixed point

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#41]
what i could find from the market loaders:

getMarketInfo - result[1]
getMarketInfo - result[5]

getMarketOutcomeInfo - result[0]
getMarketOutcomeInfo - result[1]

getParticipantSharesPurchased

**Comment by tinybike** [comment]
This isn't a bug; batch returns unprocessed values.  (It could be redesigned but I do not think this is a good use of time.)  Closing this.
