### ISSUE TITLE
account email/handle and password have hidden criteria

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#45]
there are certain account "handles" and passwords that fail registration.  it would be nice to know what those are.

i'm happy to implement a good UX and error messaging if we can come up with a reasonable set of criteria for both.

**Comment by tinybike** [comment]
As I understand it this issue is solved.  I added a note about the required password length (6 characters) in AugurProject/augur.js-docs@5235038a7952bafec49fa9336286b72da1b36faf.
