### ISSUE TITLE
Password enter slow

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur.js#47]
try entering a password in the register box by typing quickly, i.e. not like a random old person who types like a chicken pecking... it won't pickup all the letters.

**Comment by tinybike** [comment]
I'm nearly certain this is caused by excessive network I/O (so it should be improved at least somewhat by the recent networking code improvements).  Also, this is really a client issue: augur.js just handles the username/password once they're submitted.  Closing/moving this over to the client repo.
