### ISSUE TITLE
onSetup complete function does not check for valid events

### ISSUE THREAD

**Issue by eyezick** [AugurProject/augur.js#479]
Per the docs, the last argument of the `startAugurNodeEventListeners` function is :
```onSetupComplete (function) <optional> Called when all listeners are successfully set up```

In below snippet, I insert a random object and the onSetupComplete still fires. Is this the intended behavior?

```
const event = {"invalid":"event"}

augur.events.startAugurNodeEventListeners(event, function() {
      const eventName = Object.keys(event)[0]
      console.log(`Started listener for ${eventName}`);
    });

```

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14664/github-onsetup-complete-function-does-not-check-for-valid-events

**Comment by adrake33** [comment]
Thanks for bringing this to our attention, @eyezick. This function has been updated so that it now returns an error to `onSetupComplete` if the first parameter object contains any callback that are not functions.
