### ISSUE TITLE
Out of order parameters for getAllAugurLogs

### ISSUE THREAD

**Issue by eyezick** [AugurProject/augur.js#480]
Seems the error object and the resulting array of event objects are switched and being returned in the wrong variables.

The docs could just be wrong, but I see that is unlikely as the `function(err,res)` pattern is reused throughout the API.

``` 
 augur.events.getAllAugurLogs({fromBlock:2280173},function (error,logs) {
    console.log('logs type', typeof logs) // undefined
    console.log(Array.isArray(error)) // true
 
  },function(error) {
    if (error) {
      console.log(error);
    } else {
      console.log("Finished retrieving logs !!");
    }
  })
```

**Comment by pgebheim** [comment]
@adrake33 Maybe close this and move the issue into the doc repo?

Perhaps @eyezick will update the docs ;-)

**Comment by adrake33** [comment]
Closing this, as this has now been updated on docs.augur.net.
