### ISSUE TITLE
Support RPC batching?

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#5]
apparently geth supports RPC batching, but web3 does not.

i think it would be a big win for augur.js, if you could make a method like getMarkets that batches up a lot of what we're trying to do in an initial market load on the client.

this might solve the scaling issue way better than async.

**Comment by tinybike** [comment]
Do you have a reference for geth RPC batch support?  I'm googling around for it now, but not finding any good info.

**Comment by niran** [comment]
Batching is part of the JSON-RPC spec. Including multiple commands in an RPC payload should Just Work.

http://www.jsonrpc.org/specification#batch

**Comment by tinybike** [comment]
Very cool!  You were correct, I tested this via curl and it Just Worked.  I implemented a basic `batch` method in e021562e047c99a3aed144069d3d87e0b905bc56 (see README for an example of how to use it).  Will add convenience wrappers soon that don't require you to set up transaction objects.
