### ISSUE TITLE
[ethrpc] eth_subscribe request failed

### ISSUE THREAD

**Issue by Sm00g15** [AugurProject/augur.js#502]
I keep hitting this error with the code below: 
`[ethrpc] eth_subscribe request failed, fall back to polling for blocks: Method not found`
Any ideas what the issue could be?
```
var ethereumNode = { http: "https://mainnet.infura.io/augur" };
var augurNode = "wss://mainnet.infura.io/ws";

augur.connect({ ethereumNode, augurNode }, async (err, connectionInfo) => {
		if(err) {
		 console.log(err)
		} else {
		console.log(connectionInfo)
		}
	})
```

**Comment by bthaile** [comment]
https://predictions.global/augur-public-ethereum-nodes

Try using different endpoints. Infura can be unreliable.

**Comment by Sm00g15** [comment]
awesome thanks.

So for this example from that site: 
```
#1 | https://megageth.com/ | wss://megageth.com/ws
-- | -- | --

```

is it correct to use this address (wss://megageth.com/ws) as the augur node ws url?

**Comment by bthaile** [comment]
Use these endpoints for ethereum node
https://gethnode.com/http	
wss://gethnode.com/ws

you'll need to run your own augur-node
https://github.com/AugurProject/augur-node

**Comment by adrake33** [comment]
Closing this issue, as it seems to just be a matter of using different endpoints.
