### ISSUE TITLE
How to reduce node modules size?

### ISSUE THREAD

**Issue by jameswilsterman** [AugurProject/augur.js#533]
Is there any way to reduce the size of the node module dependencies?

Are these sub directories needed for example?

44MB	ethereumjs-testrpc
59MB	ethereumjs-testrpc-sc

**Comment by justinbarry** [comment]
Possibly. Are you concerned about disk space or bandwidth? The deps should cache locally so you only need to burn the bandwidth once.

The dependency tree is somewhat easy to infer from the package-lock.json file. Might be some low hanging fruit there. I’ll take a look in the morning.

**Comment by jameswilsterman** [comment]
I'm concerned about disk space. Trying to (maybe naively) run this on AWS Lambda, which requires the uncompressed deployment package to be <250 MB.

**Comment by joeykrug** [comment]
Prob not a good fit for lambda anyway, would use something else on AWS or even simpler just deploy it to digitalocean

**Comment by justinbarry** [comment]
@jameswilsterman How far did you get?

**Comment by adrake33** [comment]
@jameswilsterman Any updates on this?
