### ISSUE TITLE
Remove localstorage integration from augurjs

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#54]
Some implementers of augurjs may choose to be partially centralized, storing user accounts and other data on servers. Some may want to store data on decentralized services like storj or ipfs. Some may want to use a custom wrapper around local storage, or competing technologies that solve similar problems may emerge. 

There are good reasons to simplify augurjs and let implementers decide how to persist state. @tinybike

**Comment by tinybike** [comment]
The best way to handle persistent storage might be to offload it into a separate module entirely.  It's something that (we know from experience) is likely to change even in our own implementation.  So I think it's worth spending the time to pull the storage-related code out of both augur.js and the UI.  augur-vault, anyone?

**Comment by tinybike** [comment]
Combined with #91
