### ISSUE TITLE
p.searchQuery no effect on getMarkets()

### ISSUE THREAD

**Issue by SirLancelot-OG** [AugurProject/augur.js#546]
Current documentation states:

> p.searchQuery (string) <optional> Query string used to determine which Markets are returned by augur.markets.getMarkets. This string is used to search across Market IDs, questions, categories, tags, resolution sources, and scalar donominations.

However I am not able to filter results of `getMarkets()` with any implementation of the `searchQuery` string field. Code is as follows:

```
augur.markets.getMarkets({
  universe: universe,
  searchQuery: 'eth'
}, (error, marketIds) => {
  console.log(marketIds) // all 1200+ IDs
});
```

Is this a misunderstanding of what the `searchQuery` field does or is there an issue here? Currently there is no simple way of filtering by multiple tags or categories without multiple calls to the API.

**Comment by bthaile** [comment]
The fulltext search isnt fully documented in the api. The augur ui has a tooltip to help users find markets by searching market titles or tags or categories, ...

But the search text is translated in the UI to accommodate augur-nodes sql index fields.

 https://github.com/AugurProject/augur-node/blob/master/src/utils/content-search-builder.ts

This builds the fulltext string. 

“marketId:
    category:
    tags: 
    shortDescription: 
    longDescription: 
    resolutionSource: 
    scalarDenomination: 
“
Search string of
“tags: eth”
Should give you all markets with tag of ‘eth’

If you want all markets with ‘ethereum’ in the market title try “shortDescription: ethereum”

They can also be combined. There is an explicit AND. If you want to OR them you have to add the OR example is: “tags: eth OR shortDescription: ethereum”

**Comment by bthaile** [comment]
Also the param is called ‘search’ not searchQuery

**Comment by SirLancelot-OG** [comment]
Thanks @bthaile that's very helpful.

WTR search, are you sure that's the case? See this commit: https://github.com/AugurProject/docs/commit/8d0e420ca801ae89e20535420461bd6c669cbabe

**Comment by bthaile** [comment]
https://github.com/AugurProject/augur-node/blob/master/src/server/getters/get-markets.ts

I was looking at augur-node code.

**Comment by adrake33** [comment]
@SirLancelot-OG Yes, the parameter name should be `search`, not `searchQuery`. This has been corrected in the docs, and I've added some more info on the syntax for search queries. Apologies for the confusion.
