### ISSUE TITLE
Augur.getCreator(marketId) returns invalid creator id

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#7]
expecting:
   `0x6fc0a64e2dce367e35417bfd1568fa35af9f3e4b`
getting:
   `0x0000000000000000000000006fc0a64e2dce367e35417bfd1568fa35af9f3e4b`

**Comment by tinybike** [comment]
Fixed in ee970fd5eb4e221774c3c26ef5c2ec57d8fb4ba6.
