### ISSUE TITLE
getAccountTrades parses values wrongly

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur.js#70]
I think these lines are wrong https://github.com/AugurProject/augur.js/blob/master/src/index.js#L2134-2135: `logs[i].topics` has length 3, market ID is at index `1`. this results in `market` variable having wrong value, and `outcome` variable is always `undefined`
![account-trades-bug](https://cloud.githubusercontent.com/assets/5900808/15924334/d6dd90b4-2e31-11e6-86a1-9dabe523fcfc.png)

**Comment by tinybike** [comment]
Fixed in bb5c32b1b1984280470b78e10de03e4a8bc0fd60.
