### ISSUE TITLE
augur.connect silently fails if can't connect to websocket.

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur.js#84]
Simple reproducer

```
var options = {
    http: "http://localhost:8545",
    ws: "ws://mom",
}
augur.connect(options, (err) => {
    console.log("test");
});

```
In this example, mom is invalid. callback is never fired.

**Comment by tinybike** [comment]
Fixed in AugurProject/ethrpc@1d2bea3566c3f716cc5dc2f3e916afd9e2980162 and ethereumjs/ethereumjs-connect@57c46e0c8716f55cd7830ea5d268baab54fbc51b.
