### ISSUE TITLE
UI fee representation simplified, augurjs taking the burn

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#85]
Per https://github.com/AugurProject/augur/issues/670 we are simplifying how fees are represented in the UI to the user. Instead of having a `tradingFee` and a `makerProportionOfFee` (old maker fee) we are just going to have independent `takerFee` and `makerFee`, each a simple percentage of the total value of a trade. For example, if `takerFee` is 2% and `makerFee` is 1% a trade of 100eth will have 3eth in fees.

At the same time, the ethereum contracts will still be using the previous model, this new paradigm is for display only, so we need to have a conversion layer between the two in augurjs. 

The guiding principle:
- augurjs will only output the new fees to the ui
- augurjs will only take as input the new fees from the ui

This will need updates to the marketInfo functions and createMarket functions (and perhaps others not sure).

The formulas to convert between the paradigms is as follows:

If given the new `takerFee` and `makerFee` values:

`tradingFee = (takerFee + makerFee) / 1.5`
`makerProportionOfFee = makerFee / tradingFee`

If given the old `tradingFee` and `makerProportionOfFee` values:

`makerFee = tradingFee * makerProportionOfFee`
`takerFee = (1.5-makerFee)*tradingFee`

**Comment by tinybike** [comment]
I think the last equation should be:
```
takerFee = 1.5*tradingFee - makerFee
```

**Comment by joeykrug** [comment]
Yeah good catch

**Comment by tinybike** [comment]
Burn taken in f3eac487a8c978d22e4f955479da6a613762393a.
