### ISSUE TITLE
Change multiTrade to processOrder

### ISSUE THREAD

**Issue by priecint** [AugurProject/augur.js#86]
Since all multiTrade does is iterating user's orders ​_per outcome_​ (user trade order is actually trade transaction) and processes them (one outcome at a time) I think it would make sense to remove this iteration from multiTrade and move it to client (in our case augur).

1/ Change
`multiTrade(requestID, marketID, marketOrderBooks, userTradeOrdersPerOutcome, positionsPerOutcome, scalarMinMax, ...callbacks)`
to
`processOrder(requestID, marketID, outcomeID, outcomeOrderBook, userTradeOrder, position, scalarMinMax, ...callbacks)` (all the values are per outcome instead of maps of values for all the outcomes). processOrder contains the same logic as multiTrade except it processes one outcome, not multiple outcomes

2/ Update tests

**Comment by tinybike** [comment]
Changed in 1e88beeb33111efcaf18dc5ea9671e497a6a2194
