### ISSUE TITLE
Update login and registration logic to use `secure login id`

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#91]
Registration and login flow have been updated to generate a `secure login id`, see: https://github.com/AugurProject/augur-ui-react-components/issues/48

The `secure login id` is a base58 string representation of the json keystore users can download to populate their local geth nodes if they are using them. It looks something like:

```
{"address":"05ae1d0ca6206c6168b42efcd1fbe0ed144e821b","Crypto":{"cipher":"aes-128-cbc","ciphertext":"9c4c32f56b48db88dde445f74193c9fd630139cf6a39b9bd4264527bf931c0c3f6c8110bc0ddba5fcfe69db23ad76be2","cipherparams":{"iv":"95f5f7beca67b3920c1395e46a6f9624"},"kdf":"scrypt","kdfparams":{"n":262144,"r":8,"p":1,"dklen":32,"salt":"f9651a3b645c1898d6dddd57a2bc6540408556ce56eeb88c2952bdfc239535f1"},"mac":"0ac8678881d68f909d1f0a84b4c2ea8434393753069eac3d2ef5857f8d2ada3e","version":"1"},"id":"bd7c153f-1d11-43d6-a954-f04a61f2b715","version":"1"}"'
```
 Encoding it to base58 would be something like:

```
bs58.encode(new Buffer(myJson, 'utf8'))
```

This issue is about making registration/login understand and use this new base58 string as the username. 

Related: https://github.com/AugurProject/augur/issues/681

**Comment by thinkloop** [comment]
The API we are looking for:

```
register(password, callback) {
   return {
       secureLoginID: XXXXXXXXX,
       underlyingDataThatMadeSecureLoginID: {}
   };
}
```

```
fundAccount(address, onSent, onSuccess, onFailed)
```

```
login(secureLoginID, password)
```

**Comment by tinybike** [comment]
Added in f58582ee2ea586966c927218139dd9602b48116a
