### ISSUE TITLE
Add getMarketInfoCache to augur.js and compositeGetters contract

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur.js#92]
getMarketsInfo returns `makerFee` `takerFee` and `tradingFee`, but getMarketInfo only returns the first two.

**Comment by tinybike** [comment]
Method that only returns the specific market data that the cache node needs:
```
{tradingPeriod:1, tradingFee:1, creationTime:1, volume:1, tags:1, endDate:1, description:1, makerFee:1, takerFee:1}
```

**Comment by tinybike** [comment]
To edit contracts + push to the blockchain, you'll need to do the following:
- edit the [contract's code](https://github.com/AugurProject/augur-core/blob/master/src/functions/compositeGetters.se)
- fire up a local [geth](https://github.com/ethereum/go-ethereum) node
- load the updated script onto the blockchain using [load_contracts.py](https://github.com/AugurProject/augur-core/blob/master/load_contracts/load_contracts.py):
```
pip install -r requirements-load.txt
python load_contracts.py --contract compositeGetters
```
Next, clone [augur-contracts](https://github.com/AugurProject/augur-contracts):
```
git clone https://github.com/AugurProject/augur-contracts
```
Now run [generate_gospel.py](https://github.com/AugurProject/augur-core/blob/master/load_contracts/generate_gospel.py) to print the contract addresses in JSON format:
```
python generate_gospel.py -j
```
Copy-and-paste the new addresses to the [contracts.json](https://github.com/AugurProject/augur-contracts/blob/master/contracts.json) file.  You're using the Morden testnet, which has network ID 2, so paste these into the `"2"` key of contracts.json.

Next, run [make_api.py](https://github.com/AugurProject/augur-core/blob/master/load_contracts/make_api.py) to generate/update the static contract API file that augur.js uses:
```
python make_api.py -o /path/to/augur-contracts/api.json
```
The static data is now updated.  To use it, either `npm link augur-contracts` to use it locally from augur.js, or increment the augur-contracts npm version and publish it, then `npm update` from augur.js.  You should now have a `CompositeGetters.getMarketInfoCache` method attached to the `augur` object after you `connect`:
```javascript
var augur = require("augur.js");
var marketID = "0x...";
augur.connect({http: "http://127.0.0.1:8545", ws: "ws://127.0.0.1:8546"}, function (connection) {
    augur.CompositeGetters.getMarketInfoCache(marketID, function (marketInfo) {
        console.log(JSON.stringify(marketInfo, null, 2));
    });
});
```

**Comment by kevinday** [comment]
This has been completed with #98
